#!/usr/bin/env python

import shlex
import subprocess
import sys
import glob
import os
import re
import shutil

paths = glob.glob("UML_parser-*-with-dependencies.jar")
UML_PARSER_JAR = os.environ.get('UML_PARSER', None)
if UML_PARSER_JAR is None:
    paths = glob.glob("UML_parser-*-with-dependencies.jar")
    if paths:
        UML_PARSER_JAR = paths[0]
    else:
        print "Could not locate UML parser jar"
        exit(-1)


def parseArguments():
    # TODO validate input arguments
    return sys.argv[-2], sys.argv[-1]


def unzip(inPath):
    import zipfile
    zip_ref = zipfile.ZipFile(inPath, 'r')
    print "Unziping at %s..." % os.path.dirname(inPath)
    zip_ref.extractall(os.path.dirname(inPath))
    zip_ref.close()


def launchClassDiagramGenerator(inPath, outPath):
    return subprocess.call(shlex.split(("java -jar %s -c -i %s -o %s") %
                                       (UML_PARSER_JAR, inPath, outPath)))


def launchSequenceDiagramGenerator(inPath, outPath):
    compileAndRunAspectJ(inPath)


def compileAndRunAspectJ(inPath):
    javaFiles = glob.glob(os.path.join(inPath, "*.java"))
    for javaFile in javaFiles:
        shutil.copy(javaFile,
                    os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                 "SequenceDiagramGenerator",
                                 "src",
                                 "main",
                                 "java"))
    # TODO just compile with mvn and then run it using java
    # currently there is a bug in my SequenceDiagramGenerator.aj code
    # which does stupid things if we directly call Main class from jvm
    # instead of jvm -> junit -> test class -> Main.main()
    retval = subprocess.Popen("mvn clean test",
                              cwd=os.path.join(os.path.dirname(
                                               os.path.abspath(__file__)),
                                               "SequenceDiagramGenerator"),
                              shell=True).wait()
    if retval != 0:
        print "Error compiling!"
        exit(retval)
    for javaFile in javaFiles:
        os.remove(os.path.join(os.path.dirname(os.path.abspath(__file__)),
                               "SequenceDiagramGenerator",
                               "src",
                               "main",
                               "java",
                               os.path.basename(javaFile)))

if __name__ == '__main__':
    inPath, outPath = parseArguments()

    # Unzip if a zip file is given
    if re.match('.*\.zip', inPath):
        inPath = unzip(inPath)

    # As per the requirements, if sequence is mentioned in the input file,
    #  generate sequence diagram else class diagram
    if re.match('.*sequence.*', inPath, re.I):
        launchSequenceDiagramGenerator(inPath, outPath)
    else:
        launchClassDiagramGenerator(inPath, outPath)
